<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Consul" Version="1.6.10.8" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="6.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="6.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="6.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="6.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.2" />
    <PackageReference Include="Newtonsoft.Json.Bson" Version="1.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Modetour.B2C.Entity.Package\Modetour.B2C.Entity.Package.csproj" />
    <ProjectReference Include="..\ModetourB2C\ModetourB2C.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="ServiceDiscovery\" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Modetour.Dac">
      <HintPath>..\Modetour.Dac.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
